// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Message:
	//	*Message_Req
	//	*Message_Rsp
	//	*Message_Notify
	//	*Message_Push
	Message              isMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Message interface {
	isMessage_Message()
}

type Message_Req struct {
	Req *Req `protobuf:"bytes,1,opt,name=req,proto3,oneof"`
}

type Message_Rsp struct {
	Rsp *Rsp `protobuf:"bytes,2,opt,name=rsp,proto3,oneof"`
}

type Message_Notify struct {
	Notify *Notify `protobuf:"bytes,3,opt,name=notify,proto3,oneof"`
}

type Message_Push struct {
	Push *Push `protobuf:"bytes,4,opt,name=push,proto3,oneof"`
}

func (*Message_Req) isMessage_Message() {}

func (*Message_Rsp) isMessage_Message() {}

func (*Message_Notify) isMessage_Message() {}

func (*Message_Push) isMessage_Message() {}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetReq() *Req {
	if x, ok := m.GetMessage().(*Message_Req); ok {
		return x.Req
	}
	return nil
}

func (m *Message) GetRsp() *Rsp {
	if x, ok := m.GetMessage().(*Message_Rsp); ok {
		return x.Rsp
	}
	return nil
}

func (m *Message) GetNotify() *Notify {
	if x, ok := m.GetMessage().(*Message_Notify); ok {
		return x.Notify
	}
	return nil
}

func (m *Message) GetPush() *Push {
	if x, ok := m.GetMessage().(*Message_Push); ok {
		return x.Push
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Req)(nil),
		(*Message_Rsp)(nil),
		(*Message_Notify)(nil),
		(*Message_Push)(nil),
	}
}

type Req struct {
	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	// Types that are valid to be assigned to Req:
	//	*Req_GetUserInfoReq
	Req                  isReq_Req `protobuf_oneof:"req"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type isReq_Req interface {
	isReq_Req()
}

type Req_GetUserInfoReq struct {
	GetUserInfoReq *GetUserInfoReq `protobuf:"bytes,2,opt,name=getUserInfoReq,proto3,oneof"`
}

func (*Req_GetUserInfoReq) isReq_Req() {}

func (m *Req) GetReq() isReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *Req) GetGetUserInfoReq() *GetUserInfoReq {
	if x, ok := m.GetReq().(*Req_GetUserInfoReq); ok {
		return x.GetUserInfoReq
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Req) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Req_GetUserInfoReq)(nil),
	}
}

type GetUserInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

type Rsp struct {
	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	// Types that are valid to be assigned to Rsp:
	//	*Rsp_Error
	//	*Rsp_GetUserInfoRsp
	Rsp                  isRsp_Rsp `protobuf_oneof:"rsp"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Rsp) Reset()         { *m = Rsp{} }
func (m *Rsp) String() string { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()    {}
func (*Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsp.Unmarshal(m, b)
}
func (m *Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsp.Marshal(b, m, deterministic)
}
func (m *Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsp.Merge(m, src)
}
func (m *Rsp) XXX_Size() int {
	return xxx_messageInfo_Rsp.Size(m)
}
func (m *Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Rsp proto.InternalMessageInfo

func (m *Rsp) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type isRsp_Rsp interface {
	isRsp_Rsp()
}

type Rsp_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Rsp_GetUserInfoRsp struct {
	GetUserInfoRsp *GetUserInfoRsp `protobuf:"bytes,3,opt,name=getUserInfoRsp,proto3,oneof"`
}

func (*Rsp_Error) isRsp_Rsp() {}

func (*Rsp_GetUserInfoRsp) isRsp_Rsp() {}

func (m *Rsp) GetRsp() isRsp_Rsp {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func (m *Rsp) GetError() *Error {
	if x, ok := m.GetRsp().(*Rsp_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Rsp) GetGetUserInfoRsp() *GetUserInfoRsp {
	if x, ok := m.GetRsp().(*Rsp_GetUserInfoRsp); ok {
		return x.GetUserInfoRsp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Rsp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Rsp_Error)(nil),
		(*Rsp_GetUserInfoRsp)(nil),
	}
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetUserInfoRsp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRsp) Reset()         { *m = GetUserInfoRsp{} }
func (m *GetUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRsp) ProtoMessage()    {}
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *GetUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRsp.Unmarshal(m, b)
}
func (m *GetUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRsp.Merge(m, src)
}
func (m *GetUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRsp.Size(m)
}
func (m *GetUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRsp proto.InternalMessageInfo

func (m *GetUserInfoRsp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Notify struct {
	// Types that are valid to be assigned to Notify:
	//	*Notify_ChatNotify
	Notify               isNotify_Notify `protobuf_oneof:"notify"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Notify) Reset()         { *m = Notify{} }
func (m *Notify) String() string { return proto.CompactTextString(m) }
func (*Notify) ProtoMessage()    {}
func (*Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notify.Unmarshal(m, b)
}
func (m *Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notify.Marshal(b, m, deterministic)
}
func (m *Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notify.Merge(m, src)
}
func (m *Notify) XXX_Size() int {
	return xxx_messageInfo_Notify.Size(m)
}
func (m *Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Notify proto.InternalMessageInfo

type isNotify_Notify interface {
	isNotify_Notify()
}

type Notify_ChatNotify struct {
	ChatNotify *ChatNotify `protobuf:"bytes,1,opt,name=chatNotify,proto3,oneof"`
}

func (*Notify_ChatNotify) isNotify_Notify() {}

func (m *Notify) GetNotify() isNotify_Notify {
	if m != nil {
		return m.Notify
	}
	return nil
}

func (m *Notify) GetChatNotify() *ChatNotify {
	if x, ok := m.GetNotify().(*Notify_ChatNotify); ok {
		return x.ChatNotify
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Notify) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Notify_ChatNotify)(nil),
	}
}

type ChatNotify struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatNotify) Reset()         { *m = ChatNotify{} }
func (m *ChatNotify) String() string { return proto.CompactTextString(m) }
func (*ChatNotify) ProtoMessage()    {}
func (*ChatNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ChatNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatNotify.Unmarshal(m, b)
}
func (m *ChatNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatNotify.Marshal(b, m, deterministic)
}
func (m *ChatNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatNotify.Merge(m, src)
}
func (m *ChatNotify) XXX_Size() int {
	return xxx_messageInfo_ChatNotify.Size(m)
}
func (m *ChatNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ChatNotify proto.InternalMessageInfo

func (m *ChatNotify) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Push struct {
	// Types that are valid to be assigned to Push:
	//	*Push_ChatPush
	Push                 isPush_Push `protobuf_oneof:"push"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Push) Reset()         { *m = Push{} }
func (m *Push) String() string { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()    {}
func (*Push) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *Push) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Push.Unmarshal(m, b)
}
func (m *Push) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Push.Marshal(b, m, deterministic)
}
func (m *Push) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Push.Merge(m, src)
}
func (m *Push) XXX_Size() int {
	return xxx_messageInfo_Push.Size(m)
}
func (m *Push) XXX_DiscardUnknown() {
	xxx_messageInfo_Push.DiscardUnknown(m)
}

var xxx_messageInfo_Push proto.InternalMessageInfo

type isPush_Push interface {
	isPush_Push()
}

type Push_ChatPush struct {
	ChatPush *ChatPush `protobuf:"bytes,1,opt,name=chatPush,proto3,oneof"`
}

func (*Push_ChatPush) isPush_Push() {}

func (m *Push) GetPush() isPush_Push {
	if m != nil {
		return m.Push
	}
	return nil
}

func (m *Push) GetChatPush() *ChatPush {
	if x, ok := m.GetPush().(*Push_ChatPush); ok {
		return x.ChatPush
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Push) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Push_ChatPush)(nil),
	}
}

type ChatPush struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatPush) Reset()         { *m = ChatPush{} }
func (m *ChatPush) String() string { return proto.CompactTextString(m) }
func (*ChatPush) ProtoMessage()    {}
func (*ChatPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *ChatPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatPush.Unmarshal(m, b)
}
func (m *ChatPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatPush.Marshal(b, m, deterministic)
}
func (m *ChatPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatPush.Merge(m, src)
}
func (m *ChatPush) XXX_Size() int {
	return xxx_messageInfo_ChatPush.Size(m)
}
func (m *ChatPush) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatPush.DiscardUnknown(m)
}

var xxx_messageInfo_ChatPush proto.InternalMessageInfo

func (m *ChatPush) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Req)(nil), "pb.Req")
	proto.RegisterType((*GetUserInfoReq)(nil), "pb.GetUserInfoReq")
	proto.RegisterType((*Rsp)(nil), "pb.Rsp")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*GetUserInfoRsp)(nil), "pb.GetUserInfoRsp")
	proto.RegisterType((*Notify)(nil), "pb.Notify")
	proto.RegisterType((*ChatNotify)(nil), "pb.ChatNotify")
	proto.RegisterType((*Push)(nil), "pb.Push")
	proto.RegisterType((*ChatPush)(nil), "pb.ChatPush")
	proto.RegisterType((*String)(nil), "pb.String")
	proto.RegisterType((*User)(nil), "pb.User")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0xd3, 0x26, 0x4d, 0x9b, 0x29, 0x54, 0x2b, 0x8b, 0x43, 0xc4, 0x9f, 0x15, 0x6b, 0x56,
	0x08, 0x71, 0xa8, 0x50, 0xb9, 0x21, 0x2e, 0x5b, 0x40, 0x1b, 0x0e, 0x20, 0xe4, 0x15, 0x37, 0x24,
	0x94, 0x36, 0xb3, 0x6d, 0xd0, 0xa6, 0x71, 0x6c, 0x67, 0x25, 0x4e, 0x7c, 0x09, 0x3e, 0x30, 0xf2,
	0xd8, 0x09, 0x6d, 0x41, 0x7b, 0x8b, 0xdf, 0xef, 0xc9, 0xf3, 0x32, 0x2f, 0x81, 0xfb, 0x15, 0x6a,
	0x9d, 0x6f, 0x70, 0x2e, 0x55, 0x6d, 0x6a, 0x36, 0x94, 0x2b, 0xfe, 0x7b, 0x00, 0xe3, 0x4f, 0x4e,
	0x65, 0x8f, 0x20, 0x54, 0xd8, 0xa4, 0x83, 0xa7, 0x83, 0x17, 0xd3, 0xc5, 0x78, 0x2e, 0x57, 0x73,
	0x81, 0x4d, 0x16, 0x08, 0xab, 0x12, 0xd4, 0x32, 0x1d, 0xee, 0x41, 0x2d, 0x09, 0x6a, 0xc9, 0xce,
	0x21, 0xde, 0xd5, 0xa6, 0xbc, 0xfe, 0x99, 0x86, 0xc4, 0xc1, 0xf2, 0xcf, 0xa4, 0x64, 0x81, 0xf0,
	0x8c, 0x9d, 0x42, 0x24, 0x5b, 0xbd, 0x4d, 0x23, 0xf2, 0x4c, 0xac, 0xe7, 0x4b, 0xab, 0xb7, 0x59,
	0x20, 0x48, 0x5f, 0x26, 0x30, 0xf6, 0x01, 0xf9, 0x37, 0x08, 0x05, 0x36, 0xec, 0x04, 0xc2, 0xaa,
	0x2c, 0x28, 0x51, 0x22, 0xec, 0x23, 0x7b, 0x0b, 0xb3, 0x0d, 0x9a, 0xaf, 0x1a, 0xd5, 0xc7, 0xdd,
	0x75, 0x2d, 0xb0, 0xf1, 0x89, 0x98, 0xbd, 0xed, 0xf2, 0x80, 0x64, 0x81, 0x38, 0xf2, 0x2e, 0x47,
	0xf4, 0x86, 0xfc, 0x04, 0x66, 0x87, 0x56, 0xfe, 0x0b, 0x42, 0xa1, 0xe5, 0x7f, 0xe6, 0x9d, 0xc1,
	0x08, 0x95, 0xaa, 0x95, 0x1f, 0x93, 0xd8, 0x31, 0x1f, 0xac, 0x90, 0x05, 0xc2, 0x91, 0xe3, 0x48,
	0x5a, 0xfa, 0x25, 0xfc, 0x13, 0x89, 0xf6, 0x75, 0xe4, 0xa5, 0x48, 0x5a, 0xf2, 0x33, 0x18, 0xd1,
	0xb5, 0x2c, 0xed, 0x97, 0xe0, 0x63, 0xf4, 0x3b, 0x99, 0x1f, 0xa6, 0xd6, 0x92, 0x3d, 0x86, 0xa8,
	0xd5, 0xa8, 0x7c, 0x63, 0xb4, 0x50, 0x8b, 0x05, 0xa9, 0xfc, 0x3d, 0xc4, 0xae, 0x02, 0xf6, 0x0a,
	0x60, 0xbd, 0xcd, 0x8d, 0x3b, 0x79, 0xf7, 0xcc, 0xba, 0xdf, 0xf5, 0x6a, 0x16, 0x88, 0x3d, 0xcf,
	0x72, 0xd2, 0x15, 0xca, 0x9f, 0x03, 0xfc, 0x75, 0xdd, 0x91, 0xee, 0x0d, 0x44, 0xb6, 0x4c, 0xf6,
	0x12, 0x26, 0xf6, 0x1e, 0xfb, 0xec, 0x27, 0xdd, 0xeb, 0x26, 0xf9, 0xb2, 0x7b, 0xbe, 0x8c, 0xdd,
	0x07, 0xc1, 0xcf, 0x61, 0xd2, 0xf1, 0x3b, 0x26, 0x9c, 0x42, 0x7c, 0x65, 0x54, 0xb9, 0xdb, 0xb0,
	0x07, 0x30, 0xba, 0xcd, 0x6f, 0xda, 0xce, 0xe1, 0x0e, 0xfc, 0x07, 0x44, 0xf6, 0xed, 0xd9, 0x0c,
	0x86, 0x7d, 0x87, 0xc3, 0xb2, 0xb0, 0x6e, 0xac, 0xf2, 0xf2, 0x86, 0x2a, 0x4c, 0x84, 0x3b, 0xb0,
	0x27, 0x00, 0x6b, 0x85, 0xb9, 0xc1, 0xe2, 0x7b, 0x6e, 0xa8, 0xb1, 0x44, 0x24, 0x5e, 0xb9, 0x30,
	0x16, 0xb7, 0xb2, 0xe8, 0x70, 0xe4, 0xb0, 0x57, 0x2e, 0xcc, 0x62, 0x01, 0xd3, 0xcb, 0xbc, 0xc2,
	0x2b, 0x54, 0xb7, 0xe5, 0x1a, 0xd9, 0x33, 0x98, 0xee, 0x55, 0xc3, 0xe8, 0xf3, 0x77, 0x59, 0x1f,
	0xf6, 0xad, 0xac, 0x62, 0xfa, 0xeb, 0x5e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x24, 0x44,
	0x16, 0x86, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	GetUserInfo(ctx context.Context, in *String, opts ...grpc.CallOption) (*User, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetUserInfo(ctx context.Context, in *String, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.GameService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	GetUserInfo(context.Context, *String) (*User, error)
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) GetUserInfo(ctx context.Context, req *String) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetUserInfo(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _GameService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
